### PR TITLE
Add checks to ensure in-word formatting chars aren't replaced

### LINKED ISSUE #21: Snake_case underscores create italics
This may be out of scope for this project, but `snake_case` currently will italicize _case_. I believe underscores should only create emphasis if they're `surrounded by whitespace _like this_ `

Snarkdown: 
image

Commonmark:
image

### PR DESCRIPTION
**Pull request by jacobmischka**
I prepared this for the base repo, so it can't be automatically merged since your gross regex has some other changes, but I figured I would open it here as well in case you're interested. It should hopefully be straightforward to manually merge. Of course, feel free to close if you don't care.

Original message below.

---

Basic text formatting sequences (_, *, __, **) are now required to not
be entirely within a word; that is, they must have a non-word character
on either side to be replaced.

This prevents words that include those characters (snake_case words, or
some proper nouns that may include an Embedded*Asterisk__Or**Two for
some reason) from being captured.

Fixes #21

### CODE REVIEW

**Comment by nikku** [comment]
Thanks for your contribution! Could you elaborate what you did and why it works?

**Comment by jacobmischka** [comment]
I think I pretty much did in the commit message. It requires a non-word character (or beginning or end of input) to be on either side of the token (`_`, `*`, `__`, or `**`) in order to match.

**Comment by nikku** [comment]
You're using negative look back to filter in-word control chars. I see.

**Comment by nikku** [comment]
Given the [large number of edge cases](https://github.com/developit/snarkdown/issues/21#issuecomment-887490959) around in-word parsing I think it it makes more sense for a tiny library to invest in escaping of special chars: https://github.com/bpmn-io/snarkdown/pull/5.

**Comment by jacobmischka** [comment]
Makes sense, though might not be completely ideal if the input is user (even trusted users, if they aren't familiar with the context) provided. But yes, regardless there will be limitations in such a limited-scope library, so I understand not wanting to add too much complexity.

Anyway, like I said feel free to close if you like, it really doesn't matter to me either way. 👍

**Comment by nikku** [comment]
Closing this one for now. We may re-consider that choice with feedback we receive.

**Pull request closed without merging**
